import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    template: '%s | site',
    default: 'Next 13 + Antd 5',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <p>Aku adalah navbar</p>
        {children}
        <p>Aku adalah footer</p>
      </body>
    </html>
  );
}
